Repository BooQuest/BooQuest_Backend, pull requests merged in 2025-08, with the labels that each got.

#5 [chore] 스웨거 설정 완료
  booquest-api/build.gradle
  booquest-api/src/main/java/com/booquest/booquest_api/config/SwaggerConfig.java
Labels: chore

#18 [Feat] wireframe V3 온보딩 반영
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/OnboardingController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/dto/OnboardingDataRequest.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/persistence/UserQueryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/persistence/jpa/UserRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/CharacterPersistenceAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/jpa/CharacterRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/AiSideJobGenerator.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/character/CreateCharacterUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/dto/GenerateSideJobRequest.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/dto/SubmitOnboardingData.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/onboarding/SubmitOnboardingUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/GenerateSideJobUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/user/UpdateUserProfileUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/character/CharacterCommandPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/GenerateSideJobPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/user/UserCommandPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/user/UserQueryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/SocialLoginService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/onboarding/OnboardingService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/user/UserService.java
  booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/character/enums/CharacterType.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/character/model/UserCharacter.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/user/model/User.java
  booquest-api/src/main/resources/db/migration/V4__add_user_profile_image_social_nickname.sql
  booquest-api/src/main/resources/db/migration/V5__add_character_character_type.sql
  booquest-api/src/test/java/com/booquest/booquest_api/application/service/onboarding/OnboardingServiceIntegrationTest.java
  booquest-api/src/test/java/com/booquest/booquest_api/application/service/onboarding/OnboardingServiceTest.java
Labels: feat

#24 [Feat] 부업 재생성 기능 구현
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/sidejob/SideJobController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/sidejob/dto/RegenerateAllSideJobRequest.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/sidejob/dto/RegenerateSideJobRequest.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/AiSideJobGenerator.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/RegenerateSideJobUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/SideJobGenerationResult.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/GenerateSideJobPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/SideJobRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobService.java
  booquest-api/src/main/java/com/booquest/booquest_api/common/exception/GlobalExceptionHandler.java
  booquest-api/src/test/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobServiceTest.java
Labels: feat

#28 [Feat] 유저가 추천받은 부업들 조회 기능 구현
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/sidejob/SideJobController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/sidejob/dto/RegenerateAllSideJobRequest.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/sidejob/dto/RegenerateSideJobRequest.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/AiSideJobGenerator.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/RegenerateSideJobUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/sidejob/SelectSideJobUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/GenerateSideJobPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/SideJobRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/SelectSideJobService.java
  booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
  booquest-api/src/test/java/com/booquest/booquest_api/application/service/sidejob/GenerateSideJobServiceTest.java
Labels: feat

#29 [Feature] 부 퀘스트 상태 업데이트 (완료/완료취소 포함) API 구현
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/MissionStepController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/dto/MissionStepUpdateStatusRequest.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/dto/MissionStepUpdateStatusResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/mission/persisitence/MissionRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/missionstep/UpdateMissionStepStatusUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/missionstep/MissionStepRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/missionstep/UpdateMissionStepStatusService.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/character/model/UserCharacter.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/missionstep/model/MissionStep.java
  booquest-api/src/main/resources/application.yml
Labels: documentation, feat

#31 [Feature] 로그인한 사용자의 부업 목록 조회 API, 사용자의 부업 조회 API 구현
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/sidejob/SideJobController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/usersidejob/UserSideJobController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/usersidejob/dto/UserSideJobListResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/usersidejob/dto/UserSideJobResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/usersidejob/dto/UserSideJobSummaryResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/usersidejob/persistence/UserSideJobRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/usersidejob/persistence/UserSideJobRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/usersidejob/GetUserSideJobListUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/usersidejob/GetUserSideJobSummaryUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/usersidejob/GetUserSideJobUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/usersidejob/UserSideJobRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/usersidejob/GetUserSideJobListService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/usersidejob/GetUserSideJobService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/usersidejob/GetUserSideJobSummaryService.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/usersidejob/enums/UserSideJobStatus.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/usersidejob/model/UserSideJob.java
  booquest-api/src/main/resources/db/migration/V9__create_user_side_jobs_table.sql
Labels: feat

#33 [Feat] 온보딩 데이터 upsert 수정 & OnboardingProgressInfo 유저가 선택한 부업 아이디 응답 추가
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/OnboardingController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/dto/OnboardingProgressInfo.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/onboarding/CheckSideJobStatusUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/character/CharacterCommandPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/onboarding/OnboardingCategoryRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/SideJobRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/onboarding/OnboardingService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/CheckSideJobStatusService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/sidejob/SelectSideJobService.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/character/model/UserCharacter.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/onboarding/model/OnboardingProfile.java
  booquest-api/src/test/java/com/booquest/booquest_api/application/service/onboarding/OnboardingServiceTest.java
Labels: feat

#43 [Feature] 부업 요약 조회 API 구현
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/usersidejob/UserSideJobController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/usersidejob/dto/UserSideJobSummaryResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/income/persistence/IncomeRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/income/persistence/IncomeRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/income/IncomeRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/missionstep/MissionStepRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/usersidejob/GetUserSideJobSummaryService.java
Labels: feat

#46 [Fix] 캐릭터 디폴트 설정(임시)
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterService.java
Labels: fix

#47 [Fix] 캐릭터 디폴트 이름 설정 [Feature] 엔드포인트 변경
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/user/UserController.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterService.java
Labels: feat, fix

#55 [Feature] 수익 목록 조회 - 누적 금액 추가
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/income/web/dto/IncomeResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/income/GetIncomeListService.java
Labels: feat

#56 [Feature] 탈퇴 API 구현
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/bonus/BonusController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/user/UserController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/user/web/dto/DeleteAccountResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/TokenJpaRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/TokenRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/persistence/TokenRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/bonus/persistence/AdViewJpaRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/bonus/persistence/AdViewRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/bonus/persistence/ProofJpaRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/bonus/persistence/ProofRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/CharacterPersistenceAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/jpa/CharacterRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/income/persistence/IncomeRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/income/persistence/IncomeRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/mission/persisitence/MissionRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/mission/persisitence/MissionRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/sidejob/persistence/SideJobRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/stepprogress/StepProgressRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/stepprogress/StepProgressRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/user/persistence/UserQueryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/user/persistence/UserRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/usersidejob/persistence/UserSideJobRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/usersidejob/persistence/UserSideJobRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/userstat/UserStatRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/userstat/UserStatRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/user/DeleteAccountUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/auth/TokenRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/bonus/AdViewRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/bonus/ProofRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/character/CharacterCommandPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/income/IncomeRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/mission/MissionRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/missionstep/MissionStepRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/onboarding/OnboardingCategoryRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/onboarding/OnboardingProfileRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/sidejob/SideJobRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/stepprogress/StepProgressRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/user/UserCommandPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/usersidejob/UserSideJobRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/userstat/UserStatRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/TokenService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/income/CreateIncomeService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/onboarding/OnboardingService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/user/DeleteAccountService.java
  booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
  booquest-api/src/test/java/com/booquest/booquest_api/application/service/onboarding/OnboardingServiceIntegrationTest.java
  booquest-api/src/test/java/com/booquest/booquest_api/application/service/onboarding/OnboardingServiceTest.java
Labels: feat

#59 [fix] : missionId -> mission.id 수정
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/missionstep/persisitence/MissionStepRepository.java
Labels: fix

#60 [Refactor] Token 레포지토리 포트/어댑터 구조로 정상화
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/auth/web/dto/LogoutResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/Sha256Base64TokenHasher.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/TokenJpaRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/persistence/TokenRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/persistence/TokenRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/auth/LogoutUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/auth/TokenHashingPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/auth/TokenRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/LogoutService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/TokenService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/user/DeleteAccountService.java
  booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
Labels: refactor

#63 [Refactor] SecurityConfig - auth 및 logout 관련 수정
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/auth/web/AuthController.java
  booquest-api/src/main/java/com/booquest/booquest_api/config/SecurityConfig.java
Labels: refactor

#68 [fix] 삭제한 클래스 import 제거
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/onboarding/web/OnboardingController.java
Labels: fix

#67 [Feature] 메인퀘스트 완료 API 구현
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/MissionController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/dto/MissionCompleteResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/dto/MissionResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/dto/MissionStepUpdateStatusResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/bonus/persistence/AdViewJpaRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/bonus/persistence/AdViewRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/bonus/persistence/ProofJpaRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/bonus/persistence/ProofRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/CharacterPersistenceAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/CharacterRepository.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/character/persistence/CharacterRewardRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/mission/persisitence/MissionRepositoryAdapter.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/in/mission/CompleteMissionUseCase.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/bonus/AdViewRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/bonus/BonusStatusPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/bonus/ProofRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/character/CharacterQueryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/character/CharacterRewardPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/port/out/mission/MissionRepositoryPort.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/bonus/BonusStatusService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/character/CharacterRewardService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/mission/CompleteMissionService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/missionstep/UpdateMissionStepStatusService.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/character/enums/RewardType.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/character/policy/FixedPerCompletionPolicy.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/mission/model/Mission.java
Labels: feat

#69 [Fix] 경험치 계산 오류 수정 및 불필요한 응답값 제거
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/missionstep/dto/MissionStepUpdateStatusResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/mission/CompleteMissionService.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/missionstep/UpdateMissionStepStatusService.java
Labels: fix

#71 [Feature] 메인퀘스트 완료 응답값 status 추가
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/MissionController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/mission/dto/MissionCompleteResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/mission/CompleteMissionService.java
  booquest-api/src/main/java/com/booquest/booquest_api/domain/mission/enums/MissionCompleteStatus.java
Labels: feat

#73 [Feature] 네이버 로그인 API 구현
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/in/auth/web/AuthController.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/oauth/NaverOAuthClient.java
  booquest-api/src/main/java/com/booquest/booquest_api/adapter/out/auth/oauth/dto/NaverUserResponse.java
  booquest-api/src/main/java/com/booquest/booquest_api/application/service/auth/SocialLoginService.java
  booquest-api/src/main/resources/application.yml
  booquest-api/src/test/java/com/booquest/booquest_api/auth/application/service/SocialLoginServiceTest.java
Labels: feat
